In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import os
import re
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn import linear_model

In [2]:
#Read excel file
df=pd.read_excel(r"C:\Users\Dell\Desktop\Cost_prediction_fl.xlsx")
df

Area   Earthwork excavation  Back filling   Earth from outside    \
0     786.00                 914353         442976               407855   
1    5443.52               17849814       7,47,441            50,02,371   
2    7350.67              212124372         533333               856788   
3    1288.89                2337862         356565               189160   
4    1476.67                 545356         310826               367724   
5    2088.00                1051084         816554               873452   
6    3143.00                4055461         556000               512122   
7     656.00                 105130         123000               112000   
8    1020.00                 630780         392000               224000   
9    1176.00                 814500         317143               123232   
10   1667.67                 588711         452323               355433   
11   2566.00                1000000         328484               515789   
12   9000.00               10537138        2082578              2083578   
13   7500.00                7510000         956564               832235   
14  10000.00                8787590         912323               812526   
15   3750.00                1567560         528282               516216   
16     69.00                  45995           9718                 8005   
17    765.00                  48309          11769                64117   
18    180.00                  16328           3302                21840   
19    165.00                  10833           2101                14490   
20    662.40                  15756           8896                27752   
21   3541.00                 833906         168640              1115415   
22  10522.00               17916840         862331              2896520   
23   6382.00                 375740          75986               502583   
24   9235.00                1587421         319908              5755416   

     PCC works    RCC works  Masonry for infills  Steel in tons          Cost  
0    300622.84      7764888           2053181.75        2470000   1,26,25,719  
1   4877761.00     23717011          15573122.00        5720000   7,34,87,520  
2   8332215.00     30240545          32878584.00        6370000   9,55,58,710  
3   3131136.00      5777524           5661366.00        3965000   1,80,44,460  
4   3002990.00      7018291           7518391.00        1950000   2,05,47,380  
5   4608718.00     10718291          10119899.00        2730000   2,81,88,000  
6   4024584.00  1,82,12,333          15070000.00        5070000   4,24,30,500  
7    153162.00      4780651           3910056.00        1495000     91,84,000  
8    918972.00    63,37,560           5776688.00        5590000   1,42,80,000  
9    804060.00      7288867           7839798.00        5460000   1,64,64,000  
10  1015355.00      9990152           9277735.50        2795000   2,16,79,710  
11  4690195.00     14515534          13590998.00        4095000   3,46,41,000  
12  7550700.00     66575000          28171005.00       17875000  11,70,00,000  
13  4801278.00     46779228          36534630.00       11895000   9,75,00,000  
14  4568140.00     76058915          35144270.00       19500000  13,00,00,000  
15  4333276.00     29543561          14135905.00        5850000   5,06,25,000  
16  1733836.00       348881            316456.00         130000      9,66,000  
17   258292.00      5596690           4582090.00         130000   1,07,10,000  
18   104641.00      1507379            866510.00         195000     25,20,000  
19    75865.00      1433771            772940.00         107250     23,10,000  
20   270137.00      6021245           4722111.00         354250   1,10,65,897  
21   245355.00     28125750          16215054.00         942500   4,78,03,500  
22  4555407.00     59727401          50827501.00        7995000  13,67,86,000  
23  5774330.00     45754330          28515550.00        1755000   8,61,57,000  
24  7123369.00     48876875          51553620.00        

In [3]:
df.columns

Index(['Area ', 'Earthwork excavation ', 'Back filling  ',
       'Earth from outside  ', 'PCC works', 'RCC works', 'Masonry for infills',
       'Steel in tons', 'Cost'],
      dtype='object')

In [4]:
df_=df.replace('[^\d.]','',regex=True).astype(float)
df_

Area   Earthwork excavation   Back filling    Earth from outside    \
0     786.00               914353.0        442976.0              407855.0   
1    5443.52             17849814.0        747441.0             5002371.0   
2    7350.67            212124372.0        533333.0              856788.0   
3    1288.89              2337862.0        356565.0              189160.0   
4    1476.67               545356.0        310826.0              367724.0   
5    2088.00              1051084.0        816554.0              873452.0   
6    3143.00              4055461.0        556000.0              512122.0   
7     656.00               105130.0        123000.0              112000.0   
8    1020.00               630780.0        392000.0              224000.0   
9    1176.00               814500.0        317143.0              123232.0   
10   1667.67               588711.0        452323.0              355433.0   
11   2566.00              1000000.0        328484.0              515789.0   
12   9000.00             10537138.0       2082578.0             2083578.0   
13   7500.00              7510000.0        956564.0              832235.0   
14  10000.00              8787590.0        912323.0              812526.0   
15   3750.00              1567560.0        528282.0              516216.0   
16     69.00                45995.0          9718.0                8005.0   
17    765.00                48309.0         11769.0               64117.0   
18    180.00                16328.0          3302.0               21840.0   
19    165.00                10833.0          2101.0               14490.0   
20    662.40                15756.0          8896.0               27752.0   
21   3541.00               833906.0        168640.0             1115415.0   
22  10522.00             17916840.0        862331.0             2896520.0   
23   6382.00               375740.0         75986.0              502583.0   
24   9235.00              1587421.0        319908.0             5755416.0   

     PCC works   RCC works  Masonry for infills  Steel in tons         Cost  
0    300622.84   7764888.0           2053181.75      2470000.0   12625719.0  
1   4877761.00  23717011.0          15573122.00      5720000.0   73487520.0  
2   8332215.00  30240545.0          32878584.00      6370000.0   95558710.0  
3   3131136.00   5777524.0           5661366.00      3965000.0   18044460.0  
4   3002990.00   7018291.0           7518391.00      1950000.0   20547380.0  
5   4608718.00  10718291.0          10119899.00      2730000.0   28188000.0  
6   4024584.00  18212333.0          15070000.00      5070000.0   42430500.0  
7    153162.00   4780651.0           3910056.00      1495000.0    9184000.0  
8    918972.00   6337560.0           5776688.00      5590000.0   14280000.0  
9    804060.00   7288867.0           7839798.00      5460000.0   16464000.0  
10  1015355.00   9990152.0           9277735.50      2795000.0   21679710.0  
11  4690195.00  14515534.0          13590998.00      4095000.0   34641000.0  
12  7550700.00  66575000.0          28171005.00     17875000.0  117000000.0  
13  4801278.00  46779228.0          36534630.00     11895000.0   97500000.0  
14  4568140.00  76058915.0          35144270.00     19500000.0  130000000.0  
15  4333276.00  29543561.0          14135905.00      5850000.0   50625000.0  
16  1733836.00    348881.0            316456.00       130000.0     966000.0  
17   258292.00   5596690.0           4582090.00       130000.0   10710000.0  
18   104641.00   1507379.0            866510.00       195000.0    2520000.0  
19    75865.00   1433771.0            772940.00       107250.0    2310000.0  
20   270137.00   6021245.0           4722111.00       354250.0   11065897.0  
21   245355.00  28125750.0          16215054.00       942500.0   47803500.0  
22  4555407.00  59727401.0          50827501.00      7995000.0  136786000.0  
23  5774330.00  45754330.0          28515550.00      1755000.0   86157000.0  
24  7123369.00  48876875.0          51553620.00      5

In [10]:
X=df_[['Area ', 'Earthwork excavation ', 'Back filling  ',
       'Earth from outside  ', 'PCC works', 'RCC works', 'Masonry for infills',
       'Steel in tons']]
y=df_[['Cost']]

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.10, random_state=2)
#It creates two sets of data one is trained set and test set

In [13]:
X_train

Area   Earthwork excavation   Back filling    Earth from outside    \
6    3143.00              4055461.0        556000.0              512122.0   
23   6382.00               375740.0         75986.0              502583.0   
9    1176.00               814500.0        317143.0              123232.0   
3    1288.89              2337862.0        356565.0              189160.0   
16     69.00                45995.0          9718.0                8005.0   
12   9000.00             10537138.0       2082578.0             2083578.0   
22  10522.00             17916840.0        862331.0             2896520.0   
4    1476.67               545356.0        310826.0              367724.0   
10   1667.67               588711.0        452323.0              355433.0   
5    2088.00              1051084.0        816554.0              873452.0   
19    165.00                10833.0          2101.0               14490.0   
1    5443.52             17849814.0        747441.0             5002371.0   
2    7350.67            212124372.0        533333.0              856788.0   
7     656.00               105130.0        123000.0              112000.0   
21   3541.00               833906.0        168640.0             1115415.0   
20    662.40                15756.0          8896.0               27752.0   
18    180.00                16328.0          3302.0               21840.0   
11   2566.00              1000000.0        328484.0              515789.0   
24   9235.00              1587421.0        319908.0             5755416.0   
13   7500.00              7510000.0        956564.0              832235.0   
15   3750.00              1567560.0        528282.0              516216.0   
8    1020.00               630780.0        392000.0              224000.0   

    PCC works   RCC works  Masonry for infills  Steel in tons  
6   4024584.0  18212333.0           15070000.0      5070000.0  
23  5774330.0  45754330.0           28515550.0      1755000.0  
9    804060.0   7288867.0            7839798.0      5460000.0  
3   3131136.0   5777524.0            5661366.0      3965000.0  
16  1733836.0    348881.0             316456.0       130000.0  
12  7550700.0  66575000.0           28171005.0     17875000.0  
22  4555407.0  59727401.0           50827501.0      7995000.0  
4   3002990.0   7018291.0            7518391.0      1950000.0  
10  1015355.0   9990152.0            9277735.5      2795000.0  
5   4608718.0  10718291.0           10119899.0      2730000.0  
19    75865.0   1433771.0             772940.0       107250.0  
1   4877761.0  23717011.0           15573122.0      5720000.0  
2   8332215.0  30240545.0           32878584.0      6370000.0  
7    153162.0   4780651.0            3910056.0      1495000.0  
21   245355.0  28125750.0           16215054.0       942500.0  
20   270137.0   6021245.0            4722111.0       354250.0  
18   104641.0   1507379.0             866510.0       195000.0  
11  4690195.0  14515534.0           13590998.0      4095000.0  
24  7123369.0  48876875.0           51553620.0      5655000.0  
13  4801278.0  46779228.0           36534630.0     11895000.0  
15  4333276.0  29543561.0           14135905.0      5850000.0  
8    918972.0   6337560.0            5776688.0      5590000.0

In [14]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()  
regressor.fit(X_train, y_train) 
print("Training completed")


Training completed


In [17]:
regressor.coef_

array([[ 1.38754339e+04, -1.13366535e-02, -1.85715450e+00,
        -9.27678481e-02,  1.95698989e-01, -7.78023895e-03,
        -1.64702574e-01, -3.68077327e-02]])

In [18]:
regressor.intercept_

array([1318227.51080742])

In [22]:

y_pred=regressor.predict(X_test)

In [23]:
#Comparing actual vs predicted
y_test

Cost
14  130000000.0
0    12625719.0
17   10710000.0

In [24]:
y_pred

array([[1.31999365e+08],
       [1.09227817e+07],
       [1.11521188e+07]])

In [25]:
regressor.predict([[7350.67,212124372.0,533333.0,856788.0,8332215.00,30240545.0,32878584.00,6370000.0]])

array([[95582893.58919711]])

In [30]:
regressor.predict([[7000.0,212124372.0,533333.0,856788.0,8332215.00,30240545.0,32878584.00,6370000.0]])

array([[90717195.16894183]])

In [28]:
regressor.predict([[1288.89,2337862.0,356565.0,189160.0,3131136.00,5777524.0,5661366.00,3965000.0]])

array([[17985313.1922567]])

In [29]:
regressor.predict([[786.00,914353.0,442976.0,407855.0,300622.84,7764888.0,2053181.75,2470000.0]])

array([[10922781.66595965]])

In [31]:
regressor.predict([[10522.00,17916840.0,862331.0,2896520.0,4555407.00,59727401.0,50827501.00,7995000.0]])

array([[1.37003338e+08]])

In [26]:
from sklearn.metrics import r2_score
score=r2_score(y_test,y_pred)

In [27]:
score

0.9992403283618988